//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPandaNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int BuyerId { get; set; }
        public int SellerId { get; set; }
        public int Status { get; set; }
        public System.DateTime OrderTime { get; set; }
        public int OrderMealId { get; set; }
    
        public virtual OrderMeal OrderMeal { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
