//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPandaNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerFranchise
    {
        public int Id { get; set; }
        public int SellerId { get; set; }
        public int FranchiseId { get; set; }
        public System.DateTime DateAcquired { get; set; }
    
        public virtual Franchise Franchise { get; set; }
        public virtual User User { get; set; }
    }
}
